name: 'notify-telegram-action-flow'
description: 'Sends a Telegram message on build success or failure'
author: 'James-Kua'
branding:
  icon: 'message-circle'
  color: 'blue'
inputs:
  workflow_name:
    description: 'Name of the workflow'
    required: true
    default: 'Build'
  to:
    description: 'Telegram chat ID'
    required: true
  token:
    description: 'Telegram bot token'
    required: true
  changed_files:
    description: 'A custom list of changed files to include in the message'
    required: false
    default: ''
  message_format:
    description: 'Message format for Telegram (markdown or html)'
    required: false
    default: 'markdown'
  disable_preview:
    description: 'Disable web page preview (true/false)'
    required: false
    default: 'true'
  timezone:
    description: 'Timezone for the datetime (e.g. Asia/Singapore)'
    required: false
    default: 'Asia/Singapore'

runs:
  using: "composite"
  steps:
    - name: Set current datetime as env variable
      shell: bash
      env:
        TZ: ${{ inputs.timezone }}
      run: echo "CURRENT_DATETIME=$(date +'%d %b %Y, %I:%M%p [%A]')" >> $GITHUB_ENV

    - name: Send telegram on success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        format: ${{ inputs.message_format }}
        disable_web_page_preview: ${{ inputs.disable_preview }}
        message: |
          ✅ *${{ inputs.workflow_name }}* passed!

          ⏰ *${{ env.CURRENT_DATETIME }}*

          📂 ${{ github.head_ref || github.ref_name }}

          🧑‍💻 *${{ github.actor }}* created commit: ${{ github.event.head_commit.message }}

          🗂 *Changed files*:
          ${{ inputs.changed_files }}

          🎯 *Repository*: ${{ github.repository }}
          
          👍 *See changes*: https://github.com/${{ github.repository }}/commit/${{ github.sha }}

    - name: Send telegram on failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ inputs.to }}
        token: ${{ inputs.token }}
        format: ${{ inputs.message_format }}
        disable_web_page_preview: ${{ inputs.disable_preview }}
        message: |
          ❌ Build failed!

          ⏰ *${{ env.CURRENT_DATETIME }}*

          📂 ${{ github.head_ref || github.ref_name }}

          🧑‍💻 *${{ github.actor }}* created commit: ${{ github.event.head_commit.message }}

          🗂 *Changed files*:
          ${{ inputs.changed_files }}

          🎯 *Repository*: ${{ github.repository }}
          
          👍 *See changes*: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
